name: poetryofscience
favicon: null
layout_spectrum: 0.6185219180770218
typography_spectrum: 0.8781689037568867
title: The Poetry of Science
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-77532834-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#79b0d9'
    - '#41321b'
    - '#fffbff'
    - '#ccc194'
  brandStrength: 0.3691634254064411
  lightness: 0.12218041275627911
  saturation: 0.9551120300311595
  rhythmicContrast: 0.6424292617011815
purpose: []
